name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ========== Preparation ==========
  preparation:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.prep.outputs.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Run
        id: prep
        run: |
          RUN_ID=$(uuidgen)
          echo "Preparation stage: RunID=${RUN_ID}"
          echo "Build Number: ${{ github.run_number }}"
          echo "RunID=${RUN_ID}" > prep.txt
          echo "BuildNumber=${{ github.run_number }}" >> prep.txt
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT

      - name: Upload Prep Data
        uses: actions/upload-artifact@v4
        with:
          name: prepData
          path: prep.txt

  # ========== Parallel Jobs ==========
  jobA:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - uses: actions/checkout@v4
      - name: Download Prep Data
        uses: actions/download-artifact@v4
        with:
          name: prepData
      - name: Run JobA
        run: |
          echo "JobA running..." > JobA.log
          cat prep.txt >> JobA.log
          cat JobA.log
      - name: Upload JobA Log
        uses: actions/upload-artifact@v4
        with:
          name: JobAData
          path: JobA.log

  jobB:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - uses: actions/checkout@v4
      - name: Download Prep Data
        uses: actions/download-artifact@v4
        with:
          name: prepData
      - name: Run JobB
        run: |
          echo "JobB running..." > JobB.log
          cat prep.txt >> JobB.log
          cat JobB.log
      - name: Upload JobB Log
        uses: actions/upload-artifact@v4
        with:
          name: JobBData
          path: JobB.log

  jobC:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - uses: actions/checkout@v4
      - name: Download Prep Data
        uses: actions/download-artifact@v4
        with:
          name: prepData
      - name: Run JobC
        run: |
          echo "JobC running..." > JobC.log
          cat prep.txt >> JobC.log
          cat JobC.log
      - name: Upload JobC Log
        uses: actions/upload-artifact@v4
        with:
          name: JobCData
          path: JobC.log

  # ========== Integration ==========
  integration:
    runs-on: ubuntu-latest
    needs: [jobA, jobB, jobC]
    steps:
      - uses: actions/checkout@v4
      - name: Download Job Logs
        uses: actions/download-artifact@v4
        with:
          name: JobAData
      - uses: actions/download-artifact@v4
        with:
          name: JobBData
      - uses: actions/download-artifact@v4
        with:
          name: JobCData
      - name: Integrate Logs
        run: |
          cat JobA.log JobB.log JobC.log > combined.txt
          cat combined.txt
      - name: Upload Combined Log
        uses: actions/upload-artifact@v4
        with:
          name: integrationData
          path: combined.txt

  # ========== Deploy ==========
  deploy:
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - uses: actions/checkout@v4
      - name: Download Combined Log
        uses: actions/download-artifact@v4
        with:
          name: integrationData
      - name: Deploy Step
        run: |
          echo "Deploy step using combined results:"
          cat combined.txt
