name: CI-CD Pipeline

on:
  workflow_call:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  # ========== Preparation ==========
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Prepare Run
        id: prep
        run: |
          RUN_ID=$(uuidgen)
          echo "RunID=${RUN_ID}" > prep.txt
          echo "BuildNumber=${GITHUB_RUN_NUMBER}" >> prep.txt
          echo "RUN_ID=${RUN_ID}" >> $GITHUB_ENV
          cat prep.txt
      - name: Upload Prep Data
        uses: actions/upload-artifact@v4
        with:
          name: prepData
          path: prep.txt

  # ========== Parallel Jobs ==========
  jobA:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Download Prep Data
        uses: actions/download-artifact@v4
        with:
          name: prepData

      - name: Run JobA
        run: |
          echo "JobA running with $(cat prep.txt)" > JobA.log
          cat JobA.log

      - name: Upload JobA Log
        uses: actions/upload-artifact@v4
        with:
          name: JobAData
          path: JobA.log

  jobB:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Download Prep Data
        uses: actions/download-artifact@v4
        with:
          name: prepData

      - name: Run JobB
        run: |
          echo "JobB running with $(cat prep.txt)" > JobB.log
          cat JobB.log

      - name: Upload JobB Log
        uses: actions/upload-artifact@v4
        with:
          name: JobBData
          path: JobB.log

  jobC:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Download Prep Data
        uses: actions/download-artifact@v4
        with:
          name: prepData

      - name: Run JobC
        run: |
          echo "JobC running with $(cat prep.txt)" > JobC.log
          cat JobC.log

      - name: Upload JobC Log
        uses: actions/upload-artifact@v4
        with:
          name: JobCData
          path: JobC.log

  # ========== Integration ==========
  integration:
    runs-on: ubuntu-latest
    needs: [jobA, jobB, jobC]
    steps:
      - name: Download Job Logs
        uses: actions/download-artifact@v4
        with:
          name: JobAData
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: JobBData
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: JobCData
          path: .

      - name: Integrate Logs
        run: |
          cat JobA.log JobB.log JobC.log > combined.txt
          cat combined.txt

      - name: Upload Integration Data
        uses: actions/upload-artifact@v4
        with:
          name: integrationData
          path: combined.txt

  # ========== Deploy ==========
  deploy:
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Download Integration Data
        uses: actions/download-artifact@v4
        with:
          name: integrationData

      - name: Deploy
        run: |
          echo "Deploy step using combined results:"
          cat combined.txt
