name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Run ID
        id: prep
        run: |
          runId=$(uuidgen)
          echo "Preparation stage: RunID=$runId"
          echo "Build Number: $GITHUB_RUN_NUMBER"
          echo "RunID=$runId" > prep.txt
          echo "runId=$runId" >> $GITHUB_OUTPUT

      - name: Upload prep data (like Jenkins stash)
        uses: actions/upload-artifact@v4
        with:
          name: prepData
          path: prep.txt

  next-job:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Download prep data (unstash equivalent)
        uses: actions/download-artifact@v4
        with:
          name: prepData

      - name: Use prep data
        run: |
          echo "Contents of prep.txt:"
          cat prep.txt
          runId=$(cat prep.txt | cut -d= -f2)
          echo "Got RunID from previous job: $runId"

  parallel-jobs:
    runs-on: ubuntu-latest
    needs: preparation
    strategy:
      matrix:
        jobName: [JobA, JobB, JobC]
    steps:
      - name: Download prep data (unstash equivalent)
        uses: actions/download-artifact@v4
        with:
          name: prepData

      - name: Run job logic
        run: |
          echo "${{ matrix.jobName }} running with $(cat prep.txt)" > ${{ matrix.jobName }}.log
          echo "${{ matrix.jobName }} complete"

      - name: Upload job artifact (stash equivalent)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.jobName }}Data
          path: ${{ matrix.jobName }}.log

